"""Markdown renderers for Abel strategy-discovery generated artifacts."""

from __future__ import annotations

from pathlib import Path

from abel_invest.branch_spec import normalize_hypothesis_text, ordered_unique_strings
from abel_invest.constants import (
    AGENT_CONTEXT_FILENAME,
    DEFAULT_BACKTEST_START,
    EVIDENCE_LEDGER_FILENAME,
    FRONTIER_MARKDOWN_FILENAME,
    RESEARCH_JOURNAL_FILENAME,
)
from abel_invest.frontier import render_inline_counts, render_session_frontier_summary
from abel_invest.io import _today
from abel_invest.journal import build_research_journal_status


def render_agent_context(*, session: Path, ledger: dict, frontier: dict) -> None:
    (session / AGENT_CONTEXT_FILENAME).write_text(
        build_agent_context(session=session, ledger=ledger, frontier=frontier),
        encoding="utf-8",
    )


def build_agent_context(
    *,
    session: Path,
    ledger: dict,
    frontier: dict,
) -> str:
    rows = [row for row in (ledger.get("rows") or []) if isinstance(row, dict)]
    recent_rows = rows[-8:]
    journal_status = build_research_journal_status(session, ledger=ledger, frontier=frontier)
    return f"""# Agent Context Pack

generated by Abel strategy discovery narrative layer

## Evidence Frontier

{render_session_frontier_summary(frontier)}

## Research Journal

{render_agent_context_research_journal(journal_status)}

## Research Reflection

{render_agent_context_research_reflection(frontier)}

## Journal Coverage

{render_agent_context_journal_coverage(frontier)}

## Input Realization

{render_agent_context_input_realization(frontier)}

## Exploration Breadth

{render_agent_context_exploration_breadth(frontier)}

## Input Breadth

{render_agent_context_input_breadth(frontier)}

## Graph Priority

{render_agent_context_graph_priority(frontier)}

## Recent Evidence Rows

{render_agent_context_evidence_rows(recent_rows)}

## Evidence Sources

- ledger: `{EVIDENCE_LEDGER_FILENAME}`
- frontier: `{FRONTIER_MARKDOWN_FILENAME}`
- journal: `{RESEARCH_JOURNAL_FILENAME}`
- raw artifacts: branch `outputs/`
- session: `{session.name}`
"""


def render_agent_context_research_journal(journal_status: dict[str, object]) -> str:
    lines = [
        f"- path: `{journal_status.get('path', RESEARCH_JOURNAL_FILENAME)}`",
        f"- exists: `{str(journal_status.get('exists', False)).lower()}`",
        f"- evidence_reference_count: `{journal_status.get('evidence_reference_count', 0)}`",
        f"- resolved_evidence_reference_count: `{journal_status.get('resolved_evidence_reference_count', 0)}`",
        f"- has_evidence_linked_update: `{str(journal_status.get('has_evidence_linked_update', False)).lower()}`",
        f"- last_evidence_linked_update_line: `{journal_status.get('last_evidence_linked_update_line', 0)}`",
    ]
    excerpt = str(journal_status.get("recent_excerpt") or "").strip()
    if excerpt:
        lines.append("")
        lines.append("Recent excerpt:")
        lines.append("")
        lines.extend(f"> {line}" for line in excerpt.splitlines())
    else:
        lines.append("- recent_excerpt: `none`")
    return "\n".join(lines)


def render_agent_context_research_reflection(frontier: dict) -> str:
    reflection = frontier.get("research_reflection") or {}
    if not reflection:
        return "- not generated"
    return "\n".join(
        [
            f"- research_reflection_due: `{str(reflection.get('research_reflection_due', False)).lower()}`",
            f"- recorded_round_count: `{reflection.get('recorded_round_count', 0)}`",
            f"- journal_coverage_complete: `{str(reflection.get('journal_coverage_complete', False)).lower()}`",
            f"- missing_journal_round_count: `{reflection.get('missing_journal_round_count', 0)}`",
            f"- evidence_linked_journal_update: `{str(reflection.get('evidence_linked_journal_update', False)).lower()}`",
            f"- journal_evidence_reference_count: `{reflection.get('journal_evidence_reference_count', 0)}`",
        ]
    )


def render_agent_context_journal_coverage(frontier: dict) -> str:
    coverage = frontier.get("journal_coverage") or {}
    if not coverage:
        return "- not generated"
    return "\n".join(
        [
            f"- recorded_round_count: `{coverage.get('recorded_round_count', 0)}`",
            f"- journaled_round_count: `{coverage.get('journaled_round_count', 0)}`",
            f"- journal_coverage_complete: `{str(coverage.get('journal_coverage_complete', False)).lower()}`",
            f"- missing_journal_rounds: `{', '.join(coverage.get('missing_journal_rounds') or []) or 'none'}`",
        ]
    )


def render_agent_context_input_realization(frontier: dict) -> str:
    realization = frontier.get("input_realization") or {}
    if not realization:
        return "- not generated"
    return "\n".join(
        [
            f"- declared_graph_supported_rounds: `{realization.get('declared_graph_supported_rounds', 0)}`",
            f"- realized_graph_supported_rounds: `{realization.get('realized_graph_supported_rounds', 0)}`",
            f"- graph_input_read_gap_count: `{realization.get('graph_input_read_gap_count', 0)}`",
            f"- graph_input_read_gap_rows: `{', '.join(realization.get('graph_input_read_gap_rows') or []) or 'none'}`",
        ]
    )


def render_agent_context_exploration_breadth(frontier: dict) -> str:
    exploration = frontier.get("exploration_breadth") or {}
    if not exploration:
        return "- not generated"
    return "\n".join(
        [
            f"- branch_family_count: `{exploration.get('branch_family_count', 0)}`",
            f"- recorded_round_count: `{exploration.get('recorded_round_count', 0)}`",
            f"- same_branch_max_rounds: `{exploration.get('same_branch_max_rounds', 0)}`",
            f"- dominant_neighborhood_rows: `{exploration.get('dominant_neighborhood_rows', 0)}`",
            f"- model_family_counts: `{render_inline_counts(exploration.get('model_family_counts') or {})}`",
            f"- complexity_class_counts: `{render_inline_counts(exploration.get('complexity_class_counts') or {})}`",
            f"- exploration_class_counts: `{render_inline_counts(exploration.get('exploration_class_counts') or {})}`",
        ]
    )


def render_agent_context_input_breadth(frontier: dict) -> str:
    input_breadth = frontier.get("input_breadth") or {}
    if not input_breadth:
        return "- not generated"
    return "\n".join(
        [
            f"- input_breadth_thin: `{str(input_breadth.get('input_breadth_thin', False)).lower()}`",
            f"- input_breadth_round_minimum: `{input_breadth.get('input_breadth_round_minimum', 0)}`",
            f"- discovered_driver_count: `{input_breadth.get('discovered_driver_count', 0)}`",
            f"- discovered_drivers: `{', '.join(input_breadth.get('discovered_drivers') or []) or 'none'}`",
            f"- candidate_driver_set_count: `{input_breadth.get('candidate_driver_set_count', 0)}`",
            f"- candidate_driver_sets: `{', '.join(input_breadth.get('candidate_driver_sets') or []) or 'none'}`",
            f"- discovered_driver_coverage: `{input_breadth.get('discovered_driver_coverage', '0/0')}`",
            f"- target_only_recorded_round_count: `{input_breadth.get('target_only_recorded_round_count', 0)}`",
            f"- graph_supported_candidate_round_count: `{input_breadth.get('graph_supported_candidate_round_count', 0)}`",
        ]
    )


def render_agent_context_graph_priority(frontier: dict) -> str:
    graph_priority = frontier.get("graph_priority") or {}
    if not graph_priority:
        return "- not generated"
    return "\n".join(
        [
            f"- graph_discovery_source: `{graph_priority.get('graph_discovery_source', 'unknown')}`",
            f"- graph_discovery_k: `{graph_priority.get('graph_discovery_k', 0)}`",
            f"- graph_candidates_available: `{str(graph_priority.get('graph_candidates_available', False)).lower()}`",
            f"- graph_first_uncovered: `{str(graph_priority.get('graph_first_uncovered', False)).lower()}`",
            f"- graph_discovery_missing: `{str(graph_priority.get('graph_discovery_missing', False)).lower()}`",
            f"- target_only_saturation: `{str(graph_priority.get('target_only_saturation', False)).lower()}`",
            f"- graph_priority_round_minimum: `{graph_priority.get('graph_priority_round_minimum', 0)}`",
        ]
    )


def render_agent_context_evidence_rows(rows: list[dict]) -> str:
    if not rows:
        return "- none"
    lines = []
    for row in rows:
        lines.append(
            "- "
            f"`ledger:{row.get('branch_id', '')}:{row.get('round_id') or row.get('run_id', '')}` "
            f"label=`{row.get('evidence_label', 'unknown')}` "
            f"verdict=`{row.get('verdict', 'unknown')}` "
            f"decision=`{row.get('decision', 'unknown')}` "
            f"exploration=`{row.get('derived_exploration_class', 'unknown')}` "
            f"intent=`{row.get('declared_evidence_intent', 'unknown')}` "
            f"input=`{row.get('declared_input_claim', 'unknown')}` "
            f"workflow=`{row.get('workflow_status', 'unknown')}`"
        )
    return "\n".join(lines)


def render_round_note(**kwargs) -> str:
    result = kwargs["result"]
    metrics = result.get("metrics", {})
    requested_window = result.get("requested_window", {})
    effective_window = result.get("effective_window", {})
    diagnostics = result.get("diagnostics") or {}
    signal = diagnostics.get("signal") or {}
    actions = kwargs.get("actions") or ["Executed raw abel-edge evaluation"]
    action_lines = "\n".join(f"1. {action}" for action in actions)
    changed_dimensions = ordered_unique_strings(kwargs.get("changed_dimensions") or [])
    return f"""# {kwargs["round_id"]}

## Basic Info

- date: `{_today()}`
- ticker: `{kwargs["ticker"]}`
- exp_id: `{kwargs["exp_id"]}`
- branch_id: `{kwargs["branch_id"]}`
- mode: `{kwargs["mode"]}`
- decision: `{kwargs["decision"]}`
- score: `{result.get("score", "?/?")}`
- verdict: `{result.get("verdict", "ERROR")}`
- requested_start: `{requested_window.get("start", kwargs.get("backtest_start", DEFAULT_BACKTEST_START))}`
- requested_end: `{requested_window.get("end") or "latest"}`
- effective_window: `{effective_window.get("start", "unknown")} -> {effective_window.get("end", "unknown")}`

## Goal

`{kwargs["description"]}`

## Inputs And Hypothesis

- input: `{kwargs.get("input_note") or f"Branch {kwargs['branch_id']} entering {kwargs['round_id']}."}`
- trigger: `{kwargs.get("trigger") or kwargs["description"]}`
- hypothesis: `{normalize_hypothesis_text(kwargs.get("hypothesis", ""))}`
- expected_signal: `{kwargs.get("expected_signal") or "Improve evaluation outcome versus the current working baseline."}`

## Actions

{action_lines}

## Exploration Facts

- changed_dimensions: `{", ".join(changed_dimensions) or "none"}`

## Key Results

- lo_adjusted: `{metrics.get("lo_adjusted", 0):.3f}`
- position_ic: `{metrics.get("position_ic", 0):.4f}`
- omega: `{metrics.get("omega", 0):.3f}`
- sharpe: `{metrics.get("sharpe", 0):.3f}`
- total_return: `{metrics.get("total_return", 0) * 100:.1f}%`
- max_dd: `{metrics.get("max_dd", 0) * 100:.1f}%`
- failures: `{"; ".join(result.get("failures", [])) or "none"}`

## Diagnostics

- failure_signature: `{diagnostics.get("failure_signature", "unknown")}`
- runtime_stage: `{diagnostics.get("runtime_stage", "unknown")}`
- signal_activity: `{signal.get("active_days", 0)} / {signal.get("total_days", 0)}`
- diagnostic_hints: `{"; ".join(diagnostics.get("hints", [])) or "none"}`

## Artifacts

- context_mode: `{kwargs.get("context_mode", "injected")}`
- context_path: `{kwargs.get("context_path", "not recorded")}`
- result_path: `{kwargs.get("result_path", "not recorded")}`
- report_path: `{kwargs.get("report_path", "not recorded")}`
- handoff_path: `{kwargs.get("handoff_path", "not recorded")}`

## Conclusion

- change_summary: `{kwargs.get("change_summary") or kwargs["description"]}`
- time_spent_min: `{kwargs.get("time_spent_min") or "not recorded"}`
- summary: `{kwargs.get("summary") or f"Recorded {result.get('verdict', 'ERROR')} {result.get('score', '?/?')}."}`
- next_step: `{kwargs.get("next_step") or "not recorded"}`
"""
