"""Markdown renderers for Abel strategy-discovery generated artifacts."""

from __future__ import annotations

from pathlib import Path

from abel_invest.narrative_core.contracts.branch_spec import (
    _get_backtest_start,
    branch_declaration_status_for_branch,
    branch_selected_inputs,
    has_explicit_hypothesis,
    load_branch_spec,
    normalize_hypothesis_text,
    ordered_unique_strings,
)
from abel_invest.narrative_core.contracts.constants import (
    AGENT_CONTEXT_FILENAME,
    BRANCH_SPEC_FILENAME,
    CONTEXT_GUIDE_FILENAME,
    DATA_MANIFEST_FILENAME,
    DEFAULT_BACKTEST_START,
    DEPENDENCIES_FILENAME,
    EVIDENCE_LEDGER_FILENAME,
    EXPLORATION_PATH_FILENAME,
    EXECUTION_CONSTRAINTS_FILENAME,
    FRONTIER_MARKDOWN_FILENAME,
    FRONTIER_JSON_FILENAME,
    PROBE_SAMPLES_FILENAME,
    RUNTIME_PROFILE_FILENAME,
)
from abel_invest.narrative_core.runtime.context import (
    branch_parent_branch_id,
    format_discovery_nodes,
    format_simple_nodes,
)
from abel_invest.narrative_core.evidence.evidence import load_json_object
from abel_invest.narrative_core.evidence.exploration_path import build_exploration_path_status
from abel_invest.narrative_core.evidence.frontier import render_inline_counts, render_session_frontier_summary
from abel_invest.narrative_core.io import _today, read_tsv_rows
from abel_invest.narrative_core.contracts.paths import (
    context_guide_path,
    data_manifest_path,
    execution_constraints_path,
    probe_samples_path,
    runtime_profile_path,
)
from abel_invest.narrative_core.readiness import (
    readiness_start_covered_tickers,
    readiness_usable_tickers,
    render_discovery_readiness_section,
)
from abel_invest.narrative_core.state import (
    branch_inputs_ready,
    branch_progression,
    build_branch_snapshot_line,
    current_branch_hypothesis,
    format_risks,
    latest_debug_snapshot,
    read_round_note,
)


def render_agent_context(*, session: Path, ledger: dict, frontier: dict) -> None:
    (session / AGENT_CONTEXT_FILENAME).write_text(
        build_agent_context(session=session, ledger=ledger, frontier=frontier),
        encoding="utf-8",
    )


def build_agent_context(
    *,
    session: Path,
    ledger: dict,
    frontier: dict,
) -> str:
    rows = [row for row in (ledger.get("rows") or []) if isinstance(row, dict)]
    recent_rows = rows[-8:]
    path_status = build_exploration_path_status(session, ledger=ledger, frontier=frontier)
    return f"""# Agent Context Pack

generated by Abel Invest alpha-search narrative layer

## Evidence Frontier

{render_session_frontier_summary(frontier)}

## Exploration Path

{render_agent_context_exploration_path(path_status, frontier)}

## Input Realization

{render_agent_context_input_realization(frontier)}

## Exploration Breadth

{render_agent_context_exploration_breadth(frontier)}

## Input Breadth

{render_agent_context_input_breadth(frontier)}

## Candidate Universe

{render_agent_context_candidate_universe(frontier)}

## Recent Evidence Rows

{render_agent_context_evidence_rows(recent_rows)}

## Evidence Sources

- ledger: `{EVIDENCE_LEDGER_FILENAME}`
- frontier: `{FRONTIER_MARKDOWN_FILENAME}`
- exploration path: `{EXPLORATION_PATH_FILENAME}`
- raw artifacts: branch `outputs/`
- session: `{session.name}`
"""


def render_agent_context_input_realization(frontier: dict) -> str:
    realization = frontier.get("input_realization") or {}
    if not realization:
        return "- not generated"
    return "\n".join(
        [
            f"- declared_graph_supported_rounds: `{realization.get('declared_graph_supported_rounds', 0)}`",
            f"- realized_graph_supported_rounds: `{realization.get('realized_graph_supported_rounds', 0)}`",
            f"- graph_input_read_gap_count: `{realization.get('graph_input_read_gap_count', 0)}`",
            f"- graph_input_read_gap_rows: `{', '.join(realization.get('graph_input_read_gap_rows') or []) or 'none'}`",
        ]
    )


def render_agent_context_exploration_breadth(frontier: dict) -> str:
    exploration = frontier.get("exploration_breadth") or {}
    if not exploration:
        return "- not generated"
    return "\n".join(
        [
            f"- branch_family_count: `{exploration.get('branch_family_count', 0)}`",
            f"- recorded_round_count: `{exploration.get('recorded_round_count', 0)}`",
            f"- same_branch_max_rounds: `{exploration.get('same_branch_max_rounds', 0)}`",
            f"- dominant_neighborhood_rows: `{exploration.get('dominant_neighborhood_rows', 0)}`",
            f"- model_family_counts: `{render_inline_counts(exploration.get('model_family_counts') or {})}`",
            f"- complexity_class_counts: `{render_inline_counts(exploration.get('complexity_class_counts') or {})}`",
            f"- exploration_class_counts: `{render_inline_counts(exploration.get('exploration_class_counts') or {})}`",
        ]
    )


def render_agent_context_input_breadth(frontier: dict) -> str:
    input_breadth = frontier.get("input_breadth") or {}
    if not input_breadth:
        return "- not generated"
    return "\n".join(
        [
            f"- input_breadth_thin: `{str(input_breadth.get('input_breadth_thin', False)).lower()}`",
            f"- input_breadth_round_minimum: `{input_breadth.get('input_breadth_round_minimum', 0)}`",
            f"- discovered_driver_count: `{input_breadth.get('discovered_driver_count', 0)}`",
            f"- discovered_drivers: `{', '.join(input_breadth.get('discovered_drivers') or []) or 'none'}`",
            f"- candidate_driver_set_count: `{input_breadth.get('candidate_driver_set_count', 0)}`",
            f"- candidate_driver_sets: `{', '.join(input_breadth.get('candidate_driver_sets') or []) or 'none'}`",
            f"- discovered_driver_coverage: `{input_breadth.get('discovered_driver_coverage', '0/0')}`",
            f"- target_only_recorded_round_count: `{input_breadth.get('target_only_recorded_round_count', 0)}`",
            f"- graph_supported_candidate_round_count: `{input_breadth.get('graph_supported_candidate_round_count', 0)}`",
        ]
    )


def render_agent_context_candidate_universe(frontier: dict) -> str:
    candidate_universe = frontier.get("candidate_universe") or {}
    input_breadth = frontier.get("input_breadth") or {}
    if not candidate_universe:
        return "- not generated"
    return "\n".join(
        [
            f"- graph_discovery_source: `{candidate_universe.get('graph_discovery_source', 'unknown')}`",
            f"- graph_discovery_k: `{candidate_universe.get('graph_discovery_k', 0)}`",
            f"- graph_candidates_available: `{str(candidate_universe.get('graph_candidates_available', False)).lower()}`",
            f"- target_only_recorded_round_count: `{candidate_universe.get('target_only_recorded_round_count', input_breadth.get('target_only_recorded_round_count', 0))}`",
            f"- graph_supported_candidate_round_count: `{candidate_universe.get('graph_supported_candidate_round_count', input_breadth.get('graph_supported_candidate_round_count', 0))}`",
            f"- candidate_driver_set_count: `{candidate_universe.get('candidate_driver_set_count', input_breadth.get('candidate_driver_set_count', 0))}`",
            f"- discovered_driver_coverage: `{candidate_universe.get('discovered_driver_coverage', input_breadth.get('discovered_driver_coverage', '0/0'))}`",
        ]
    )


def render_agent_context_evidence_rows(rows: list[dict]) -> str:
    if not rows:
        return "- none"
    lines = []
    for row in rows:
        lines.append(
            "- "
            f"`ledger:{row.get('branch_id', '')}:{row.get('round_id') or row.get('run_id', '')}` "
            f"label=`{row.get('evidence_label', 'unknown')}` "
            f"verdict=`{row.get('verdict', 'unknown')}` "
            f"decision=`{row.get('decision', 'unknown')}` "
            f"exploration=`{row.get('derived_exploration_class', 'unknown')}` "
            f"intent=`{row.get('declared_evidence_intent', 'unknown')}` "
            f"input=`{row.get('declared_input_claim', 'unknown')}` "
            f"workflow=`{row.get('workflow_status', 'unknown')}`"
        )
    return "\n".join(lines)


def render_agent_context_exploration_path(status: dict[str, object], frontier: dict) -> str:
    coverage = frontier.get("path_coverage") or {}
    lines = [
        f"- path: `{status.get('path', EXPLORATION_PATH_FILENAME)}`",
        f"- exists: `{str(status.get('exists', False)).lower()}`",
        f"- entry_count: `{status.get('entry_count', 0)}`",
        f"- evidence_reference_count: `{status.get('evidence_reference_count', 0)}`",
        f"- resolved_evidence_reference_count: `{status.get('resolved_evidence_reference_count', 0)}`",
        f"- recorded_round_count: `{coverage.get('recorded_round_count', 0)}`",
        f"- covered_round_count: `{coverage.get('covered_round_count', 0)}`",
        f"- path_coverage_complete: `{str(coverage.get('path_coverage_complete', False)).lower()}`",
        f"- missing_path_rounds: `{', '.join(coverage.get('missing_path_rounds') or []) or 'none'}`",
        f"- next_edge_run_prompt: read `{EXPLORATION_PATH_FILENAME}` and latest Edge result artifacts before choosing the next strategy",
    ]
    excerpt = str(status.get("recent_excerpt") or "").strip()
    if excerpt:
        lines.append("")
        lines.append("Recent excerpt:")
        lines.append("")
        lines.extend(f"> {line}" for line in excerpt.splitlines())
    else:
        lines.append("- recent_excerpt: `none`")
    return "\n".join(lines)


def _round_dsr_accounting(result: dict, accounting: object) -> dict[str, object]:
    if isinstance(accounting, dict):
        return accounting
    metrics = result.get("metrics") if isinstance(result.get("metrics"), dict) else {}
    k_detail = result.get("K_detail") if isinstance(result.get("K_detail"), dict) else {}
    declared = (
        k_detail.get("declared_dsr_trials")
        if isinstance(k_detail.get("declared_dsr_trials"), dict)
        else {}
    )
    components = declared.get("components") if isinstance(declared.get("components"), dict) else {}
    return {
        "edge_k": result.get("K"),
        "edge_dsr_trials_used": metrics.get("dsr_trials_used"),
        "edge_k_source": k_detail.get("source"),
        "alpha_declared_count": declared.get("count"),
        "alpha_current_round_trials": components.get("current_round_trials"),
        "alpha_prior_effective_trials": components.get("prior_effective_trials"),
    }


def _render_dsr_value(value: object) -> str:
    if value is None or value == "":
        return "unknown"
    return str(value)


def render_round_note(**kwargs) -> str:
    result = kwargs["result"]
    metrics = result.get("metrics", {})
    requested_window = result.get("requested_window", {})
    effective_window = result.get("effective_window", {})
    diagnostics = result.get("diagnostics") or {}
    signal = diagnostics.get("signal") or {}
    actions = kwargs.get("actions") or ["Executed raw abel-edge evaluation"]
    action_lines = "\n".join(f"1. {action}" for action in actions)
    changed_dimensions = ordered_unique_strings(kwargs.get("changed_dimensions") or [])
    dsr_accounting = _round_dsr_accounting(result, kwargs.get("dsr_accounting"))
    return f"""# {kwargs["round_id"]}

## Basic Info

- date: `{_today()}`
- ticker: `{kwargs["ticker"]}`
- exp_id: `{kwargs["exp_id"]}`
- branch_id: `{kwargs["branch_id"]}`
- mode: `{kwargs["mode"]}`
- decision: `{kwargs["decision"]}`
- score: `{result.get("score", "?/?")}`
- verdict: `{result.get("verdict", "ERROR")}`
- requested_start: `{requested_window.get("start", kwargs.get("backtest_start", DEFAULT_BACKTEST_START))}`
- requested_end: `{requested_window.get("end") or "latest"}`
- effective_window: `{effective_window.get("start", "unknown")} -> {effective_window.get("end", "unknown")}`

## Goal

`{kwargs["description"]}`

## Inputs And Candidate Note

- input: `{kwargs.get("input_note") or f"Branch {kwargs['branch_id']} entering {kwargs['round_id']}."}`
- trigger: `{kwargs.get("trigger") or kwargs["description"]}`
- candidate_note: `{normalize_hypothesis_text(kwargs.get("hypothesis", ""))}`
- expected_signal: `{kwargs.get("expected_signal") or "Improve evaluation outcome versus the current working baseline."}`

## Actions

{action_lines}

## Exploration Facts

- changed_dimensions: `{", ".join(changed_dimensions) or "none"}`
- K: `{_render_dsr_value(dsr_accounting.get("edge_k"))}`
- dsr_trials_used: `{_render_dsr_value(dsr_accounting.get("edge_dsr_trials_used"))}`
- K_source: `{_render_dsr_value(dsr_accounting.get("edge_k_source"))}`
- current_round_trials: `{_render_dsr_value(dsr_accounting.get("alpha_current_round_trials"))}`
- prior_effective_trials: `{_render_dsr_value(dsr_accounting.get("alpha_prior_effective_trials"))}`

## Key Results

- lo_adjusted: `{metrics.get("lo_adjusted", 0):.3f}`
- position_ic: `{metrics.get("position_ic", 0):.4f}`
- omega: `{metrics.get("omega", 0):.3f}`
- sharpe: `{metrics.get("sharpe", 0):.3f}`
- total_return: `{metrics.get("total_return", 0) * 100:.1f}%`
- max_dd: `{metrics.get("max_dd", 0) * 100:.1f}%`
- failures: `{"; ".join(result.get("failures", [])) or "none"}`

## Diagnostics

- failure_signature: `{diagnostics.get("failure_signature", "unknown")}`
- runtime_stage: `{diagnostics.get("runtime_stage", "unknown")}`
- signal_activity: `{signal.get("active_days", 0)} / {signal.get("total_days", 0)}`
- diagnostic_hints: `{"; ".join(diagnostics.get("hints", [])) or "none"}`

## Artifacts

- context_mode: `{kwargs.get("context_mode", "injected")}`
- context_path: `{kwargs.get("context_path", "not recorded")}`
- result_path: `{kwargs.get("result_path", "not recorded")}`
- report_path: `{kwargs.get("report_path", "not recorded")}`
- handoff_path: `{kwargs.get("handoff_path", "not recorded")}`

## Conclusion

- change_summary: `{kwargs.get("change_summary") or kwargs["description"]}`
- time_spent_min: `{kwargs.get("time_spent_min") or "not recorded"}`
- summary: `{kwargs.get("summary") or f"Recorded {result.get('verdict', 'ERROR')} {result.get('score', '?/?')}."}`
- next_step: `{kwargs.get("next_step") or "not recorded"}`
"""


def build_session_readme(
    session: Path,
    discovery: dict,
    readiness: dict,
    branches: list[dict],
) -> str:
    keep_branches = [
        branch
        for branch in branches
        if branch["rows"] and branch["rows"][-1].get("decision") == "keep"
    ]
    discard_branches = [
        branch
        for branch in branches
        if branch["rows"] and branch["rows"][-1].get("decision") == "discard"
    ]
    recorded_round_count = sum(len(branch["rows"]) for branch in branches)
    debugged_branches = [
        branch for branch in branches if latest_debug_snapshot(branch["branch_dir"])
    ]
    frontier = load_json_object(session / FRONTIER_JSON_FILENAME)
    executive = "No validated evidence rows yet."
    if branches and not any(branch["rows"] for branch in branches):
        executive = f"{len(branches)} branch(es) have been initialized, but no validated rounds exist yet."
        if debugged_branches:
            latest_debug_branch = max(
                debugged_branches,
                key=lambda branch: latest_debug_snapshot(branch["branch_dir"]).get("updated_at", ""),
            )
            debug_note = latest_debug_snapshot(latest_debug_branch["branch_dir"])
            executive += (
                f" {len(debugged_branches)} branch(es) have already been debugged; "
                f"latest blocker is `{latest_debug_branch['branch_id']}` with signature "
                f"`{debug_note.get('failure_signature', 'unknown')}`."
            )
        else:
            executive += " Evidence labels remain empty until a runtime result is recorded."
    elif recorded_round_count:
        executive = (
            f"Session has {len(branches)} branch(es) and {recorded_round_count} recorded round(s): "
            f"{len(keep_branches)} keep and {len(discard_branches)} discard. "
            "Evidence labels, coverage, and runtime facts are summarized below without ranking branches by metrics."
        )

    branch_lines = (
        "\n".join(
            (
                f"1. `{branch['branch_id']}` - {len(branch['rows'])} rounds, latest "
                f"`{branch['rows'][-1].get('round_id', 'none')}` {branch['rows'][-1].get('decision', 'pending')}"
                if branch["rows"]
                else (
                    f"1. `{branch['branch_id']}` - pending, latest debug "
                    f"`{latest_debug_snapshot(branch['branch_dir']).get('failure_signature', 'not run')}`"
                    if latest_debug_snapshot(branch["branch_dir"])
                    else f"1. `{branch['branch_id']}` - scaffolded, no rounds or debug runs yet"
                )
            )
            for branch in branches
        )
        or "1. `No branches yet.`"
    )

    snapshot_lines = (
        "\n".join(
            line
            for branch in branches
            for line in (
                [build_branch_snapshot_line(branch)]
                if branch["rows"]
                else (
                    [
                        (
                            f"1. `{branch['branch_id']}` -> `debug` / "
                            f"`{latest_debug_snapshot(branch['branch_dir']).get('verdict', 'ERROR')}` / "
                            f"signature `{latest_debug_snapshot(branch['branch_dir']).get('failure_signature', 'unknown')}`. "
                            f"Why: `{current_branch_hypothesis(branch['branch_dir'], branch['rows']) or latest_debug_snapshot(branch['branch_dir']).get('summary', 'not recorded')}`."
                        )
                    ]
                    if latest_debug_snapshot(branch["branch_dir"])
                    else []
                )
            )
        )
        or "1. `No branch outcomes yet.`"
    )
    activity_lines = (
        "\n".join(
            format_event_line(row) for row in read_tsv_rows(session / "events.tsv")[-5:]
        )
        or "1. `No events yet.`"
    )

    return f"""# {discovery.get("ticker", session.parent.name.upper())} Exploration Session {session.name}

generated by Abel strategy discovery narrative layer

## Executive Summary

{executive}

## Session Summary

- ticker: `{discovery.get("ticker", session.parent.name.upper())}`
- exp_id: `{session.name}`
- started_at: `{discovery.get("created_at", "unknown")}`
- discovery_source: `{discovery.get("source", "unknown")}`
- backtest_start: `{_get_backtest_start(discovery)}`
- current_status: `{"has_keep" if keep_branches else "active" if branches else "exploring"}`
- branch_count: `{len(branches)}`
- exploration_path: `{EXPLORATION_PATH_FILENAME}`

## Session Goal

Explore {discovery.get("ticker", session.parent.name.upper())} in session `{session.name}` using discovery source `{discovery.get("source", "unknown")}` and compare candidate branches through validated rounds.

Before choosing the next Edge run, read `{EXPLORATION_PATH_FILENAME}` and the latest Edge result artifacts.

## Discovery Readiness

{render_discovery_readiness_section(readiness)}

## Evidence State

This session tracks {len(branches)} branch(es). Current outcomes: {len(keep_branches)} keep, {len(discard_branches)} discard, {len(branches) - len(keep_branches) - len(discard_branches)} pending.

{render_session_frontier_summary(frontier)}

## Branches

{branch_lines}

## Branch Outcome Snapshot

{snapshot_lines}

## Recent Activity

{activity_lines}
"""


def build_branch_readme(branch: dict, latest_note: dict[str, str], exp_id: str) -> str:
    rows = branch["rows"]
    latest = rows[-1] if rows else {}
    debug_note = latest_debug_snapshot(branch["branch_dir"])
    diagnostics_note = latest_note or debug_note
    keep_rows = [row for row in rows if row.get("decision") == "keep"]
    branch_hypothesis = current_branch_hypothesis(branch["branch_dir"], rows)
    parent_branch_id = branch_parent_branch_id(branch["branch_dir"])
    declaration = branch_declaration_status_for_branch(branch["branch_dir"])
    protocol_gaps = ", ".join(str(item) for item in declaration["protocol_gaps"]) or "none"
    ledger = (
        "\n".join(
            f"1. `{row.get('round_id', '?')}` - {row.get('description', '?')} [{row.get('score', '?')}] {row.get('decision', '?')}"
            for row in rows
        )
        or "`No rounds yet.`"
    )
    return f"""# {branch["branch_id"]}

generated by Abel strategy discovery narrative layer

## Basic Info

- branch_id: `{branch["branch_id"]}`
- ticker: `{latest.get("ticker", branch["ticker"])}`
- exp_id: `{exp_id}`
- evidence_intent: `{declaration["evidence_intent"] or "not_declared"}`
- input_claim: `{declaration["input_claim"] or "not_declared"}`
- mechanism_family: `{declaration["mechanism_family"] or "not_declared"}`
- declaration_audit_complete: `{declaration["protocol_complete"]}`
- declaration_audit_gaps: `{protocol_gaps}`
- parent_branch_id: `{parent_branch_id or 'none'}`
- current_status: `{latest.get("decision", "debugged" if debug_note else "scaffolded" if not rows else "exploring")}`
- total_rounds: `{len(rows)}`
- latest_round: `{latest.get("round_id", "debug" if debug_note else "none")}`
- validation_status: `{latest.get("verdict", diagnostics_note.get("verdict", "not_validated"))}`

## Branch Candidate Note

See `branch.yaml` for explicit branch inputs and legacy-named `thesis.md` for
the branch candidate note.

## Latest Conclusion

- decision: `{latest.get("decision", "pending")}`
- summary: `{latest.get("description", diagnostics_note.get("summary", "No rounds recorded yet."))}`
- evidence_label_source: `{EVIDENCE_LEDGER_FILENAME}`

## Latest Diagnostics

- failure_signature: `{diagnostics_note.get("failure_signature", "not recorded")}`
- runtime_stage: `{diagnostics_note.get("runtime_stage", "not recorded")}`
- signal_activity: `{diagnostics_note.get("signal_activity", "not recorded")}`
- diagnostic_hints: `{diagnostics_note.get("diagnostic_hints", "not recorded")}`

## Latest Artifacts

- alpha_context_mode: `{diagnostics_note.get("context_mode", "not recorded")}`
- alpha_context: `{diagnostics_note.get("context_path", "not recorded")}`
- branch_spec: `{BRANCH_SPEC_FILENAME}`
- prepared_inputs: `{"inputs/" if branch_inputs_ready(branch["branch_dir"]) else "not prepared"}`
- runtime_profile: `{"inputs/" + RUNTIME_PROFILE_FILENAME if runtime_profile_path(branch["branch_dir"]).exists() else "not prepared"}`
- execution_constraints: `{"inputs/" + EXECUTION_CONSTRAINTS_FILENAME if execution_constraints_path(branch["branch_dir"]).exists() else "not prepared"}`
- data_manifest: `{"inputs/" + DATA_MANIFEST_FILENAME if data_manifest_path(branch["branch_dir"]).exists() else "not prepared"}`
- context_guide: `{"inputs/" + CONTEXT_GUIDE_FILENAME if context_guide_path(branch["branch_dir"]).exists() else "not prepared"}`
- probe_samples: `{"inputs/" + PROBE_SAMPLES_FILENAME if probe_samples_path(branch["branch_dir"]).exists() else "not prepared"}`
- edge_result: `{diagnostics_note.get("result_path", latest.get("result_path", "not recorded"))}`
- edge_report: `{diagnostics_note.get("report_path", latest.get("report_path", "not recorded"))}`
- edge_handoff: `{diagnostics_note.get("handoff_path", latest.get("handoff_path", "not recorded"))}`

## Decision Rationale

1. latest_candidate_note: `{branch_hypothesis or latest_note.get("hypothesis", "not recorded")}`
1. latest_summary: `{diagnostics_note.get("summary", latest.get("description", "not recorded"))}`
1. latest_failures: `{diagnostics_note.get("failures", "none")}`
1. candidate_note_status: `{"explicit" if has_explicit_hypothesis(branch_hypothesis) else "needs work"}`

## Round Ledger

{ledger}

## Metric Progression

{branch_progression(rows)}

## Baseline

- keep_rounds: `{len(keep_rows)}`
- latest_keep: `{keep_rows[-1].get("round_id", "none") if keep_rows else "none"}`
"""


def build_thesis(branch: dict, discovery: dict, readiness: dict) -> str:
    rows = branch["rows"]
    latest = rows[-1] if rows else {}
    hypothesis = current_branch_hypothesis(branch["branch_dir"], rows)
    branch_spec = load_branch_spec(branch["branch_dir"])
    latest_note = (
        read_round_note(branch["branch_dir"], latest.get("round_id", ""))
        if latest
        else {}
    )
    parents = format_discovery_nodes(discovery.get("parents", []), limit=5)
    blanket = format_discovery_nodes(discovery.get("blanket_new", []), limit=5)
    usable = format_simple_nodes(readiness_usable_tickers(readiness), limit=8)
    start_covered = format_simple_nodes(readiness_start_covered_tickers(readiness), limit=8)
    selected = format_simple_nodes(branch_selected_inputs(branch_spec), limit=8)
    return f"""# {branch["branch_id"]} Candidate Note

generated by Abel Invest alpha-search narrative layer

## Alpha Source

Branch `{branch["branch_id"]}` is currently searching: `{hypothesis or latest.get("description", "Initial branch candidate note not recorded yet")}`.
Latest decision is `{latest.get("decision", "pending")}` with verdict `{latest.get("verdict", "not_validated")}`.

## Audit Checklist

- search objective: `state the target behavior or edge being tested`
- expected sign / regime: `state when the signal should be long, short, or flat`
- invalidation condition: `state what evidence would make this candidate unconvincing`

## Input Universe

- target: `{discovery.get("ticker", branch["ticker"])}`
- discovery_source: `{discovery.get("source", "unknown")}`
- direct_parents: `{parents}`
- mb_bucket_candidates: `{blanket}`
- selected_inputs: `{selected}`
- usable_tickers: `{usable}`
- start_covered_tickers: `{start_covered}`

## Main Risks

{format_risks(latest_note.get("failures", "none"))}
"""


def format_event_line(row: dict[str, str]) -> str:
    tail = " ".join(
        part
        for part in (
            row.get("branch_id", ""),
            row.get("round_id", ""),
            row.get("decision", ""),
        )
        if part
    )
    return f"1. `{row.get('timestamp', '')}` {row.get('event', '')} {tail} - {row.get('description', '')}".rstrip()
